service: express-app
provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: ap-southeast-2
  memorySize: 128
  architecture: arm64
functions:
  app:
    handler: app/app.handler
    url: true
